### ISSUE TITLE
Dolibarr version 20.0.0

### ISSUE THREAD

**Issue by michalhana99** [sonikf/ctpt#11]
In version 20.0.0, no option can be selected, an error is displayed when creating the design
"Error in request SELECT id as rowid, libelle FROM llx_c_typent AND Filter error - Bad syntax of the search string ORDER BY libelle You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND Filter error - Bad syntax of the search string ORDER BY libelle' at line 1. Check setup of extra parameters."

![image](https://github.com/user-attachments/assets/4c01da9c-98ea-4acf-8250-301ee8d11afb)

**Comment by sonikf** [comment]
Hi @michalhana99 
Sorry for the late response!
Unfortunately due to breaking changes in Dolibarr core, on how it handles extrafield filters this module will start supporting v 20 from next release v 20.0.1
Fortunately there is a workaround till then

> ⚠️ *WARNING* This only apply to Dolibarr v 20.0.0 and CTPT v 1.0.4

You have to manually edit 
/custom/core/modules/modCTPT.class.php file
and change

`$param['options']['c_typent:libelle:id::active=1)'] = '';`

with

`$param['options']['c_typent:libelle:id::(active:=:1)'] = '';`

**and also replace** core file htdocs/core/class/extrafields.class.php with

https://github.com/Dolibarr/dolibarr/blob/develop/htdocs/core/class/extrafields.class.php
